api_platform:
    title: 'API => Portforlio Dg-Web.fr'
    description: 'API for my portfolio'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/json']
    swagger:
        versions: [3]